name:                hs-libp2p
version:             0.1.0.0
github:              "githubuser/hs-libp2p"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2018 Author name here"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/hs-libp2p#readme>

dependencies:
- base >= 4.7 && < 5
- hs-multihash


library:
  source-dirs: src
  dependencies:
   - bytestring
   - bytes
   - binary
   - containers
   - cryptonite

tests:
  hs-libp2p-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hs-libp2p
