resolver: lts-12.0

extra-deps:
 - base58-bytestring-0.1.0
 - cryptostore-0.2.0.0
 - x509-1.7.5
 - hs-multihash
 - hs-multiaddr
 - network-3.0.1.1
 - io-streams-1.5.1.0

packages:
 - .
# - hs-multihash
#- hs-multiaddr